name: Auto UAE Tax Blogs

on:
  schedule:
    - cron: '0 6 * * *'

  workflow_dispatch:

jobs:
  update-blog:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install axios
        env:
  GROQ_API_KEY: ${{ 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 }}
  NEWS_API_KEY: ${{ aa8784ca4feb42a0af0cc261654374fc }}

      - name: Generate Blogs
        run: node generateBlogs.js

      - name: Commit Changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add blogs.json

          git commit -m "Auto update UAE tax blogs" || echo "No changes"

          git push
